#!/bin/bash
CONFIG_HOME="${HOME}/.config/"
# NVIM_HOME="${CONFIG_HOME}/nvim/"

# Get the current location of this bash script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_BACKUP="${DIR}/config/"
ZSH_BACKUP="${DIR}/zsh"
AWS_BACKUP="${DIR}/aws"
GIT_BACKUP="${DIR}/git"
LOCAL_BACKUP="${DIR}/local"

ACTION=$1

# Determine the operating system (either `linux` or `darwin` or `windows`)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

if [ "$OS" == "linux" ]; then
    if [ -f /etc/os-release ]; then 
        if grep -q 'ID=ubuntu' /etc/os-release; then
            DISTRO="ubuntu"
        elif grep -q 'ID=debian' /etc/os-release; then
            DISTRO="debian"
        fi
    else
        DISTRO="unknown"
    fi
fi

# List of linux packages to install
APT_PACKAGES=(
    git
    curl
    wget
    python3
    python-dev
    python-pip
    python3-dev
    python3-pip
    zsh
    grep
    awk
    software-properties-common
)

# List of mac packages to install
HOMEBREW_PACKAGES=(
    git
)

# List of directories to be stashed
CONFIG_BACKUP_DIRS=(
    nvim
    gh
)

main() {
    echo "You are running the following OS: ${OS}"

    # run ensure_prerequisites
    ensure_prerequisites

    if [ "$ACTION" == "stash" ]; then
        run_stash
        exit 0
    fi

    if [ "$ACTION" == "install" ]; then
        run_install
        exit 0
    fi

    if [ "$ACTION" == "restore" ]; then
        run_restore
        exit 0
    fi

    echo "Please run one of \`cfg [stash|restore|install]\`"
}

run_stash() {
    # Loop through CONFIG_BACKUP_DIRS and backup each directory
    for config_backup_dir in "${CONFIG_BACKUP_DIRS[@]}"; do
        if [ -d "${CONFIG_HOME}/${config_backup_dir}" ]; then
            echo "Backing up ${config_backup_dir} config..."
            mkdir -p "${CONFIG_BACKUP}/${config_backup_dir}"
            cp -r "${CONFIG_HOME}/${config_backup_dir}/" "${CONFIG_BACKUP}/${config_backup_dir}/"
        fi
    done

    # Backup zsh
    echo "Backing up zsh config..."
    mkdir -p "${ZSH_BACKUP}"
    cp -r "${HOME}/.zshrc" "${ZSH_BACKUP}/.zshrc"
    cp -r "${HOME}/.zsh_profile" "${ZSH_BACKUP}/.zsh_profile"
    cp -r "${HOME}/.zprofile" "${ZSH_BACKUP}/.zprofile"

    # Backup banner
    echo "Backing up banner..."
    cp -r "${HOME}/.banner" "${DIR}/.banner"

    # Backup aws config
    echo "Backing up aws config..."
    mkdir -p "${AWS_BACKUP}"
    cp -r "${HOME}/.aws/config" "${AWS_BACKUP}/config"

    # Backup git config
    echo "Backing up git config..."
    mkdir -p "${GIT_BACKUP}/${OS}"
    cp -r "${HOME}/.gitconfig" "${GIT_BACKUP}/${OS}/.gitconfig"

    # backup scritps
    echo "Backing up scripts..."
    mkdir -p "${LOCAL_BACKUP}/scripts"
    cp -r "${HOME}/.local/scripts/" "${LOCAL_BACKUP}/scripts/"
}

run_restore() {
    # restore config from backup
    for dir in "${CONFIG_BACKUP_DIRS[@]}"; do
        if [ -d "${CONFIG_BACKUP}/${dir}" ]; then
            echo "Restoring ${dir} config..."
            mkdir -p "${CONFIG_HOME}/${dir}"
            cp -r "${CONFIG_BACKUP}/${dir}" "${CONFIG_HOME}/"
        fi
    done

    # Restore zsh
    echo "Restoring zsh config..."
    cp -r "${ZSH_BACKUP}/.zshrc" "${HOME}/.zshrc"
    cp -r "${ZSH_BACKUP}/.zsh_profile" "${HOME}/.zsh_profile"
    cp -r "${ZSH_BACKUP}/.zprofile" "${HOME}/.zprofile"

    # Restore banner
    echo "Restoring banner..."
    cp -r "${DIR}/.banner" "${HOME}/.banner"

    # Restore aws config
    echo "Restoring aws config..."
    mkdir -p "${HOME}/.aws"
    cp -r "${AWS_BACKUP}/config" "${HOME}/.aws/config"

    # Restore git config
    echo "Restoring git config..."
    cp -r "${GIT_BACKUP}/${OS}/.gitconfig" "${HOME}/.gitconfig"

    # Restore scripts
    echo "Restoring scripts..."
    mkdir -p "${HOME}/.local/scripts"
    cp -r "${LOCAL_BACKUP}/scripts/" "${HOME}/.local/scripts/"

    echo "Restoring complete!"
    echo "Run \`cfg install\` to install packages"
}

run_install() {
    # TODO: Implement install functionality
    echo "Installing packages..."

    if [ "$OS" == "linux" ]; then
        # TODO: add support for RPM, ARCH, and NIX
        if has_apt; then
            install_debian
        else
            echo "apt not found! Bailing out!"
            exit 1
        fi
    elif [ "$OS" == "darwin" ]; then
        install_mac
    elif [ "$OS" == "windows" ]; then
        install_windows
    fi

    # TODO: instal zsh, zsh theme, neovim, python3
    
    # TODO: install for linux dev servers: fonts, nextcloud, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install for linux desktops: kitty, fonts, nextcloud, vscode-insiders, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install for mac iterm2, fonts, nexcloud, vscode-insiders, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install ocaml
    # TODO: install golang
    # TODO: install nvm
    # TODO: Add seafile drive : https://help.seafile.com/drive_client/drive_client_for_linux/ 
}

install_debian() {
    sudo apt update
    echo "Do you want to upgrade all your packages before getting started? (recommended)"
    read -n 1 -p "Upgrade packages? (y/n)" res_char
    echo " "
    if [ "$res_char" == "y" ]; then
        sudo apt upgrade -y
        echo "******* upgrade complete *******\n"
    fi

    echo "Installing base packages..."
    echo "The following packages will be installed if not present: ${APT_PACKAGES[@]}"
    echo "Do you want to continue? (if not will skip to next step)"
    read -n 1 -p "Install base packages? (y/n)" res_char
    echo " "
    if [ "$res_char" == "y" ]; then
        sudo apt-get install -y "${APT_PACKAGES[@]}"
        echo "******* base packages installed *******\n"
    fi

    # Now install special stuff
    if has_oh_my_zsh; then
        echo "oh-my-zsh already installed! Skipping..."
    else
        echo "Installing oh-my-zsh..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        echo "******* oh-my-zsh installed! *******\n"
    fi
    install_zsh_theme

    # echo "TODO: Activate oh-my-zsh"
    # Check if shell is zsh, if not, activate
    if [ -n "$ZSH_VERSION" ]; then
        echo "Zsh is already activated"
    else
        echo "Activating zsh..."
        chsh -s $(which zsh)
        echo "******* Zsh activated! *******\n"
    fi

    if has_neovim; then
        echo "Neovim already installed! Skipping..."
    else
        # Install neovim
        echo "Installing Neovim from nightly (gotta do nightly, sorry)..."
        # mkdir -p /tmp/nvim
        # wget -O /tmp/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
        # tar -xzf /tmp/nvim-linux64.tar.gz -C /tmp/nvim
        wget -O /tmp/nvim.appimage https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        sudo mkdir -p /usr/local/lib/neovim
        sudo mv /tmp/nvim.appimage /usr/local/lib/neovim/nvim.appimage
        sudo chmod 755 /usr/local/lib/neovim/nvim
        sudo ln -s /usr/local/lib/neovim/nvim /usr/local/bin/nvim
        echo "******* Neovim installed! *******\n"
    fi

    

    # Install gh
    if has_gh; then
        echo "gh already installed! Skipping..."
    else
        echo "Install Github Client? (recommended)"
        read -n 1 -p "Install gh? (y/n)" res_char
        echo " "
        if [ "$res_char" == "y" ]; then
            echo "Installing gh..."
            type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
            echo "******* gh installed! *******\n"
        fi
    fi

    # Install docker
    if docker_installed; then
        echo "Docker already installed! Skipping..."
    else
        echo "Install Docker? (recommended)"
        read -n 1 -p "Install Docker? (y/n)" res_char
        echo " "
        if [ "$res_char" == "y" ]; then
            echo "Installing Docker..."


            echo "Setup docker group for non-root access? (recommended)"
            read -n 1 -p "Setup docker group? (y/n)" res_char
            echo " "
            if [ "$res_char" == "y" ]; then
                if getent group docker > /dev/null; then
                    echo "docker group already exists, adding user ..."
                else
                    sudo groupadd docker
                fi
                sudo usermod -aG docker $USER
                newgrp docker
                echo "******* Docker group setup! *******\n"
            fi

            sudo apt-get remove docker docker-engine docker.io containerd runc
            sudo apt-get update
            sudo apt-get install \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg \
                lsb-release
            sudo install -m 0755 -d /etc/apt/keyrings

            if [ "$DISTRO" == "ubuntu" ]; then
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            elif [ "$DISTRO" == "debian" ]; then
                curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            else
                curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            fi

            sudo chmod a+r /etc/apt/keyrings/docker.gpg


            if [ "$DISTRO" == "ubuntu" ]; then
                echo \
                    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            elif [ "$DISTRO" == "debian" ]; then
                echo \
                    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
                    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null    
            else
                echo \
                    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
                    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            fi

            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            echo "******* Docker installed! *******\n"
        fi
    fi

    # Install lolcat
    if command -v lolcat > /dev/null; then
        echo "lolcat already installed! Skipping..."
    else
        echo "Install lolcat? (recommended)"
        read -n 1 -p "Install lolcat? (y/n)" res_char
        echo " "
        if [ "$res_char" == "y" ]; then
            echo "Installing lolcat..."
            wget -O /tmp/figurine_linux_v1.2.1.tar.gz https://github.com/arsham/rainbow/releases/download/v1.2.1/figurine_linux_v1.2.1.tar.gz
            mkdir -p /tmp/figurine
            tar -xzf /tmp/figurine_linux_v1.2.1.tar.gz -C /tmp/figurine
            sudo mkdir -p /usr/local/lib/figurine
            sudo mv /tmp/figurine/deploy/rainbow /usr/local/lib/figurine/rainbow
            sudo chmod 755 /usr/local/lib/figurine/rainbow
            ln -s /usr/local/lib/figurine/rainbow /usr/local/bin/lolcat
            echo "******* lolcat installed! *******\n"
        fi
    fi

    # Install build-essential
    echo "Do you want to install build essentials? (recommended if not a ops server)"
    read -n 1 -p "Install build-essential? (y/n)" res_char
    echo " "
    if [ "$res_char" == "y" ]; then
        sudo apt-get install build-essential
    fi

    # Install nvm
    echo "TODO: Install nvm and node"

    echo "TODO: Install golang"

    echo "TODO: Install ocaml"

    echo "TODO: Install rust toolchain"

    echo "TODO: Install zig toolchain"

    echo "TODO: Install seadrive"



    # TODO: instal zsh, zsh theme, neovim, python3
    
    # TODO: install for linux dev servers: fonts, nextcloud, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install for linux desktops: kitty, fonts, nextcloud, vscode-insiders, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install for mac iterm2, fonts, nexcloud, vscode-insiders, nvm, gh, docker, docker-compose, golang, build-essential, lolcat
    # TODO: install ocaml
    # TODO: install golang
    # TODO: install nvm
    # TODO: Add seafile drive : https://help.seafile.com/drive_client/drive_client_for_linux/ 
}

install_mac() {
    echo "not implemented for mac. Bailing out!"
    exit 1
}
install_windows() {
    echo "not implemented for windows. Bailing out!"
    exit 1
}

ensure_prerequisites() {
    # Check if git is installed
    if ! [ -x "$(command -v git)" ]; then
        echo "Git not installed! Installing git ..." >&2
        install_git
    fi

    if [ "$OS" == "darwin" ]; then
        ensure_mac_prequisites
    elif [ "$OS" == "windows" ]; then
        ensure_windows_prequisites
    fi
}

ensure_mac_prequisites() {
    # Check if brew is installed
    if ! [ -x "$(command -v brew)" ]; then
        echo "Homebrew not installed! Installing homebrew ..." >&2
        exit 1
    fi
}
ensure_windows_prequisites() {
    # Check if choco is installed
    if ! [ -x "$(command -v choco)" ]; then
        echo "Chocolatey not installed! Installing chocolatey ..." >&2
        install_choco
    fi
}

install_git() {
    # Install git
    if [ "$OS" == "linux" ]; then
        sudo apt-get install git
    elif [ "$OS" == "darwin" ]; then
        xcode-select --install
    elif [ "$OS" == "windows" ]; then
        choco install git
    fi
}

# Only run on macOS
install_homebrew() {
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    
}

install_choco() {
    powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
}

has_apt() {
    if command -v apt > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

has_curl() {
    if command -v curl > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

has_python3() {
    if command -v python3 > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

has_zsh() {
    if command -v zsh > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

has_oh_my_zsh() {
    if [ -d "${HOME}/.oh-my-zsh" ]; then
        return 1 # true
    else
        return 0 # false
    fi
}
has_neovim() {
    if command -v nvim > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

has_gh() {
    if command -v gh > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

docker_installed() {
    if command -v docker > /dev/null; then
        return 1 # true
    else
        return 0 # false
    fi
}

install_zsh_theme() {
    REQUIRED_THEME=$(grep '^ZSH_THEME=\"' $DIR/zsh/.zshrc | awk -F'"' '{print $2}')
    if [ -d "${HOME}/.oh-my-zsh/custom/themes/${REQUIRED_THEME}" ]; then
        echo "ZSH theme ${REQUIRED_THEME} already installed! Skipping..."
        return 0 # true
    else
        echo "Installing ZSH theme ${REQUIRED_THEME}..."
        if [ "$REQUIRED_THEME" == "powerlevel10k/powerlevel10k" ]; then 
            git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
            echo "In theory if you run \`p10k configure\` if you're fonts are weird you should be good to go!"
            echo "******* ZSH theme ${REQUIRED_THEME} installed! *******"
            return 0 # true
        fi
    fi

    echo "Warning could not install ZSH theme ${REQUIRED_THEME}! Unknown theme!"

    return 1 # false
}

# Exec starts here


main
